# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stackit < Formula
  desc "Command-line tool for managing stacked changes in Git"
  homepage "https://github.com/getstackit/stackit"
  version "0.15.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/getstackit/stackit/releases/download/v0.15.11/stackit_Darwin_x86_64.tar.gz"
      sha256 "e07a98c380035d79eeb7779ebfa6d775f5c8c74b24db8638b5be1fb20c3d4d12"

      def install
        bin.install "stackit"
        bin.install_symlink "stackit" => "st"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/getstackit/stackit/releases/download/v0.15.11/stackit_Darwin_arm64.tar.gz"
      sha256 "3e8245be22708c1d34d84b9a0c4f3ca450194335aead8ba430b1636feb8c6a47"

      def install
        bin.install "stackit"
        bin.install_symlink "stackit" => "st"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/getstackit/stackit/releases/download/v0.15.11/stackit_Linux_x86_64.tar.gz"
      sha256 "b7a41547814e72edc07b39d698ac8fa69f231d66c19f26c573133aa9d528986a"
      def install
        bin.install "stackit"
        bin.install_symlink "stackit" => "st"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/getstackit/stackit/releases/download/v0.15.11/stackit_Linux_arm64.tar.gz"
      sha256 "96b5dd033dc1ec60a8e918810b0e2498ca36ff406bf85299561df7f47edf71c1"
      def install
        bin.install "stackit"
        bin.install_symlink "stackit" => "st"
      end
    end
  end

  test do
    system "#{bin}/stackit", "--version"
  end
end
