# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stackit < Formula
  desc "Command-line tool for managing stacked changes in Git"
  homepage "https://github.com/jonnii/stackit"
  version "0.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jonnii/stackit/releases/download/v0.11.0/stackit_Darwin_x86_64.tar.gz"
      sha256 "efa0f220d83f764f8496ca365e2267c14d8d79ad1c1072665dfcbadbdde3c595"

      def install
        bin.install "stackit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jonnii/stackit/releases/download/v0.11.0/stackit_Darwin_arm64.tar.gz"
      sha256 "fec0a1e4cde218ae9d94461ce2286f11af6590d7240954cd8af6b824c12cf3be"

      def install
        bin.install "stackit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jonnii/stackit/releases/download/v0.11.0/stackit_Linux_x86_64.tar.gz"
      sha256 "cd6f3ba21769eb3b0e1fe1153299c34ad0c26d7cb8efd78848b0fa570eea8fd5"
      def install
        bin.install "stackit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jonnii/stackit/releases/download/v0.11.0/stackit_Linux_arm64.tar.gz"
      sha256 "5e7ff00efbea930c44956f54797ddfbcdaa0fe547eb9e84da00f784b3d14cd2f"
      def install
        bin.install "stackit"
      end
    end
  end

  test do
    system "#{bin}/stackit", "--version"
  end
end
